name: optimized_gesture_detector
description: a optimized class on flutter GestureDector
version: 0.0.6
author: SunPointed<410338643@qq.com>
homepage: https://github.com/SunPointed/OptimizedGestureDetector

environment:
  sdk: '>=2.17.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
